// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPn_z5tuUmBCAVVZLRto9sRHntih7nXZ4',
    appId: '1:470931265978:web:a6c94147f29e0441aaa583',
    messagingSenderId: '470931265978',
    projectId: 'smart-notes-backend-aba3e',
    authDomain: 'smart-notes-backend-aba3e.firebaseapp.com',
    storageBucket: 'smart-notes-backend-aba3e.firebasestorage.app',
    measurementId: 'G-KJDLLVR8M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStncIFT61iqgY6McCcwzM6MGp8fXxWwc',
    appId: '1:470931265978:android:1c7bf4ea96576af4aaa583',
    messagingSenderId: '470931265978',
    projectId: 'smart-notes-backend-aba3e',
    storageBucket: 'smart-notes-backend-aba3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu95vpEepCyzHsl_tr0P0vuSJkUCzLHYY',
    appId: '1:470931265978:ios:066c3ec312312499aaa583',
    messagingSenderId: '470931265978',
    projectId: 'smart-notes-backend-aba3e',
    storageBucket: 'smart-notes-backend-aba3e.firebasestorage.app',
    iosBundleId: 'com.example.smartNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu95vpEepCyzHsl_tr0P0vuSJkUCzLHYY',
    appId: '1:470931265978:ios:066c3ec312312499aaa583',
    messagingSenderId: '470931265978',
    projectId: 'smart-notes-backend-aba3e',
    storageBucket: 'smart-notes-backend-aba3e.firebasestorage.app',
    iosBundleId: 'com.example.smartNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPn_z5tuUmBCAVVZLRto9sRHntih7nXZ4',
    appId: '1:470931265978:web:a28d2af188f5d71eaaa583',
    messagingSenderId: '470931265978',
    projectId: 'smart-notes-backend-aba3e',
    authDomain: 'smart-notes-backend-aba3e.firebaseapp.com',
    storageBucket: 'smart-notes-backend-aba3e.firebasestorage.app',
    measurementId: 'G-94B25PGG4V',
  );
}
